name: Profolio CI Checks

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-portfolio:
        uses: somasundar-dev/devops-toolkit/.github/workflows/angular-ci.yaml@main
        with:
            node_version: '19'

    